version: '3.7'

services: 
  db:
    image: postgres
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    tty: true
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    command: rails server -b 0.0.0.0
  front: 
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/bus-schedule-app:/usr/src/app
    command: yarn dev
    ports:
      - "8000:3000"
volumes:
  postgres-db:
    driver: local

